### ISSUE TITLE
Не использовать fsconverter.ltx

### ISSUE THREAD

**Issue by PavelBlend** [abramcumner/xray_re-tools#10]
Удалить файл fsconverter.ltx и вместо него использовать fs.ltx из СДК. Для чего это нужно:
если пользователь изменил пути в fs.ltx для СДК на свои, то ему придётся повторно изменять эти пути и для fsconverter.ltx. Иначе в СДК будет две папки с логами (одна от СДК, вторая от конвертера). И вообще, зачем нужен fsconverter.ltx, если он по содержанию идентичен fs.ltx из СДК? Можно дать возможность указывать путь к fs.ltx в converter.ini, а fsconverter.ltx вообще удалить.

**Comment by abramcumner** [comment]
Есть ключ запуска -fs [путь к fs.ltx].

**Comment by PavelBlend** [comment]
Про ключ fs не знал. Он не описан в converter.txt. Только описан в консоли, если запустить конвертер без ключей. Но я по привычке пользуюсь converter.txt, так как не силён в английском. Было бы лучше, если бы все ключи были описаны в txt файле на русском.
