### ISSUE TITLE
Обновить документацию из docs

### ISSUE THREAD

**Issue by PavelBlend** [abramcumner/xray_re-tools#11]
Обновить документацию из docs\tools\. Описать все новые ключи. Например, не описан ключ terrain в converter.txt. Может ещё что-то не описано?

**Comment by RayTwitty** [comment]
Еще K.D. добавлял ключ all для получения всех анимаций отдельными файлами из ogf(omf?).
Конечно, нужно бы собрать изменения и обновить ридми по фичам.

**Comment by abramcumner** [comment]
> Еще K.D. добавлял ключ all для получения всех анимаций отдельными файлами из ogf(omf?).
> Конечно, нужно бы собрать изменения и обновить ридми по фичам.

`-skl *` должно так работать.

**Comment by RayTwitty** [comment]
> > Еще K.D. добавлял ключ all для получения всех анимаций отдельными файлами из ogf(omf?).
> > Конечно, нужно бы собрать изменения и обновить ридми по фичам.
> 
> `-skl *` должно так работать.

https://github.com/abramcumner/xray_re-tools/commit/b467be5d53db5ef7e0c23dffc23458ddf540385a#diff-fa66e436df44c109bc02d7fb1b1a01feR84

Насколько я вижу, ключ all тоже присутствует. Раз уж есть регулярки, то наверно можно его убрать. Вероятность анимации с именем "all" хоть и мала, но всё же есть... Или переименовать в "_all_" или типа того.

**Comment by abramcumner** [comment]
Да пусть остается, раз уж есть :)

**Comment by PavelBlend** [comment]
@abramcumner а сейчас конвертер поддерживает метки анимаций из ogf v4+ (ЧН, ЗП)?
Вот здесь описано:
https://github.com/abramcumner/xray_re-tools/blob/b42cc142ea59460d2eb3d24f89b7ffb86027c194/docs/tools/converter.txt#L48

Если поддерживается, то нужно удалить это замечание.

**Comment by abramcumner** [comment]
вроде как поддерживаются, но я не проверял.
