### ISSUE TITLE
Ключ out для распаковки архивов

### ISSUE THREAD

**Issue by PavelBlend** [abramcumner/xray_re-tools#15]
Привет, @abramcumner 

Я сейчас распаковываю архивы из билдов. Для распаковки пользуюсь питоновским скриптом, чтобы вручную не делать этого. При распаковке конвертер не позволяет указать место, куда сохранять результат. Можно ли сделать ключ out рабочим для unpack режима? Просто при распаковке всё складируется в одну папку, а мне это не нужно. У меня команды выглядят примерно так:

`converter -unpack "папка_с_билдами\номер_билда\gamedata.db№" -2947ru`

Мне нужно результат распаковки сохранить в:
`папка_с_билдами\номер_билда\gamedata_№\`

Я конечно могу в питоне сделать перемещение папки в нужное место, но я думаю это улучшение облегчит работу не только мне.

**Comment by abramcumner** [comment]
Привет!
По идее ключ -dir делает то, что тебе нужно.

converter -unpack "папка_с_билдами\номер_билда\gamedata.db№" -2947ru -dir папка_с_билдами\номер_билда\gamedata_№

**Comment by PavelBlend** [comment]
Понял. Не знал. Читал ридми к конвертеру и в нём ни слова об этом ключе. Только если запустить конвертер без ключей выводится описание dir ключа. Но я как то привык в ридми читать. Думал он актуален и в нём есть описание всех ключей.
