### ISSUE TITLE
Сборка в Linux

### ISSUE THREAD

**Issue by smalcom** [abramcumner/xray_re-tools#23]
День добрый.
Увидел, что уже используется cmake и не смог пройти мимо. Хоть время не стоит на месте и компиляторы меняются, но верил, что получится.

### Приключение I. Компиляция.

1. Включить "unistd.h", иначе не видит getpid и т. п.

https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/3rd%20party/nvtt/nvcore/Debug.cpp#L38

2. Современный gcc строже следит за типами: надо возвращать nullptr

https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/3rd%20party/nvtt/nvimage/ImageIO.cpp#L138
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/3rd%20party/nvtt/nvimage/ImageIO.cpp#L236
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/3rd%20party/nvtt/nvimage/ImageIO.cpp#L257
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_file_system.cxx#L238

3. Не нашло "config_types.h". Понятно, что надо сходить и запустить "./configure" в каталоге libogg. Но надо исправить  файлы с "виндовыми" окончаниями строки:
dos2unix configure
dos2unix config.sub
dos2unix config.guess

4. Написало
> #warning unexpected build environment
Для добавления Linux'а:
-#elif defined(__MINGW32__)
+#elif defined(__MINGW32__) || defined(__linux__)

Были и в других местах подобные предупреждения - просто комментировал их.

5. Список инициализации в "for" может содержать только один тип. Наверное использовалась какое-то расширение MSVC.
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_writer.h#L274

В следующей функции уже написано правильно
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_writer.h#L288

6. В Linux - это "strcasecmp".
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_string_utils.h#L31

7. xr_file_system_win32.h и xr_file_system_win32.cxx завернул в
#if defined(_MSC_VER)

8. Эта возможность тянется ещё из языка "B". Её не рекомендовано использовать, т. к. в стандарте она не определена и зависит от компилятора.
Макроопределния "U" и "L" не помогли: мой gcc упорно начал считать такие константы размером 16 бит. Решил просто подавить предупреждение с xray_re\CMakeLists.txt:
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-multichar")

9. Компилятор не нашёл базовую функцию в
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_influence.h#L25

Включаем принудительно:
	using _svector<_bone_weight<Tb, Tw>, 4>::push_back;

10. Используется переопределение
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/3rd%20party/nvtt/nvmath/nvmath.h#L94

но цель несколькими строчками выше выключена
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/3rd%20party/nvtt/nvmath/nvmath.h#L51

В дополнение к этому, её нужно завернуть в пространство имён "std".

11. Надо std::type_info
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_scene.cxx#L454

12. В Linux'е это "snprintf"
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_scene_ways.cxx#L86

13. format.c_str()
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/xray_re/xr_writer.cxx#L195

14. Регистр в именах важен.
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/opcode/OPC_AABBCollider.cpp#L31
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/opcode/OPC_IceHook.h#L24
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/opcode/OPC_IceHook.h#L66
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/opcode/OPC_AABBTree.cpp#L47
и т. д.

15.
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/opcode/OPC_IceHook.h#L35

gcc не понимает обратной косой черты в пути. Правим:
sed -i '/#include/s/\\/\//g' *.h

16.
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/opcode/Ice/IceTypes.h#L52

Включаем "stdint.h" и используем типы, которые есть везде - int64_t, uint64_t.

17. Предупреждение, что оператор преобразования к базовому типу никогда не будет использован:
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/opcode/Ice/IceHPoint.h#L150

просто закомментировал эту строку.

18. Завернул в _MSC_VER
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/db_tools.cxx#L2

и получил кучу ошибок, т. к. этот файл не имеет версии для Linux. Включил C++17 и заменил обход каталогов на:
	fs::path fullpath(m_root + path);

	if(!fs::exists(fullpath) || !fs::is_directory(fullpath))
		return;

	for(auto const& de: fs::recursive_directory_iterator(fullpath))
	{
		if(de.is_regular_file())
			process_file(de.path());
	}

То же самое проделал в "dds_tools.cxx", "ogg_tools.cxx".

19.
https://github.com/abramcumner/xray_re-tools/blob/2222ad023c0656cbbdbe7e93d59f7bed29387e5d/sources/utils/converter/level_tools.cxx#L285

Заменил на
std::string version = m_ini->r_string(m_sect_profile, "spawn_version");

### Приключение II. Компоновка.

1. Оказалось, что xr_file_system_posix.cxx пустой. Переходим на C++17 и заполняем файл.

xr_file_system_posix.h:
```
#ifndef __GNUC__
#pragma once
#endif
#ifndef __XR_FILE_SYSTEM_POSIX_H__
#define __XR_FILE_SYSTEM_POSIX_H__

#include "xr_file_system.h"

#include <stdio.h>

namespace xray_re {

class xr_file_writer_posix: public xr_writer
{
public:
	xr_file_writer_posix();
	xr_file_writer_posix(FILE* p_FD);
	virtual	~xr_file_writer_posix();
	virtual void w_raw(const void* src, size_t src_size);
	virtual void seek(size_t pos);
	virtual size_t tell();

private:
	FILE* m_FD;
};

} // end of namespace xray_re

#endif
```

xr_file_system_posix.cxx:
```
#include "xr_file_system_posix.h"

#include <filesystem>

#include <errno.h>
#include <unistd.h>
#include <sys/stat.h>

using namespace xray_re;
namespace fs = std::filesystem;


bool xr_file_system::create_folder(const char* path) const
{
	if (read_only()) {
		dbg("fs_ro: creating folder %s", path);
		return true;
	}

	fs::path opath(path);

	if(fs::exists(opath))
		return true;

	return fs::create_directory(opath);
}

bool xr_file_system::create_path(const char* path) const
{
	if (read_only()) {
		dbg("fs_ro: creating path %s", path);
		return true;
	}

	fs::path opath(path);

	if(fs::exists(opath))
		return true;

	return fs::create_directories(opath);
}

void xr_file_system::split_path(const char* path, std::string* folder, std::string* name, std::string* extension)
{
fs::path opath(path);

	if(folder != nullptr)
		folder->assign(opath.parent_path());

	if(name != nullptr)
		name->assign(opath.stem());

	if(extension != nullptr)
		extension->assign(opath.extension());
}

bool xr_file_system::folder_exist(const char* path)
{
fs::path opath(path);

	return fs::exists(opath) && fs::is_directory(opath);
}

bool xr_file_system::file_exist(const char* path)
{
fs::path opath(path);

	return fs::exists(opath) && fs::is_regular_file(opath);
}

size_t xr_file_system::file_length(const char* path)
{
fs::path opath(path);

	return fs::file_size(opath);
}

uint32_t xr_file_system::file_age(const char* path)
{
struct stat st;

	if(stat(path, &st) == 0)
		return uint32_t(st.st_mtime);

	return 0;
}

bool xr_file_system::copy_file(const char* src_path, const char* tgt_path) const
{
	if (read_only()) {
		dbg("fs_ro: copying %s to %s", src_path, tgt_path);
		return true;
	}

fs::path from(src_path), to(tgt_path);

	return fs::copy_file(from, to);
}

xr_reader* xr_file_system::r_open(const char* path) const
{
using namespace std;

fs::path opath(path);
xr_reader* r = nullptr;
uint8_t* data;
uintmax_t len;

	len = fs::file_size(opath);
	if(len > numeric_limits<uint32_t>::max())
		return nullptr;

	data = (uint8_t*)malloc(len);
	if(data != nullptr)
	{
		FILE* infile = fopen(path, "r");

		if((infile != nullptr) && (fread(data, 1, len, infile) == len))
			r = new xr_temp_reader(data, len);
		else
			free(data);
	}

	return r;
}

xr_writer* xr_file_system::w_open(const char* path, bool ignore_ro) const
{
FILE* outfile;

	if (!ignore_ro && read_only()) {
		dbg("fs_ro: writing %s", path);
		return new xr_fake_writer();
	}

	outfile = fopen(path, "w");
	if(outfile == nullptr)
	{
		if(errno == ENOENT)
		{
			fs::path p(path);

			if(!fs::create_directories(p.parent_path()))
				return nullptr;

			return w_open(path, ignore_ro);
		}
		else
		{
			return nullptr;
		}
	}

	xr_writer* w = new xr_file_writer_posix(outfile);

	if(w == nullptr)
		fclose(outfile);

	return w;
}

xr_file_writer_posix::xr_file_writer_posix()
	: m_FD(nullptr)
{}

xr_file_writer_posix::xr_file_writer_posix(FILE* p_FD)
	: m_FD(p_FD)
{}

xr_file_writer_posix::~xr_file_writer_posix()
{
	if(m_FD != nullptr)
		fclose(m_FD);
}

void xr_file_writer_posix::w_raw(const void* data, size_t size)
{
	xr_assert(fwrite(data, 1, size, m_FD) == size);
}

void xr_file_writer_posix::seek(size_t pos)
{
	xr_assert(fseek(m_FD, pos, SEEK_SET) == 0);
}

size_t xr_file_writer_posix::tell()
{
	return ftell(m_FD);
}
```

2. В "3rdparty/CMakeLists.txt" после
add_library(nvtt STATIC)
добавить
target_link_libraries(nvtt PRIVATE nvimage)

т. к. там циклическая зависимость.

-------------
И?

> [converter]$ cat /etc/os-release
> NAME="ALT"
> VERSION="10.3"
> ...
> [converter]$ ./converter
> X-Ray game asset converter (A.0.2.0 May 26 2024)
> Vendor: ZENOBIAN mod team
> Usage: converter <common-options> <format-specific-options> <input-objects>
> ...
>

**Comment by Xottab-DUTY** [comment]
Пул-реквест бы)

**Comment by abramcumner** [comment]
@smalcom очень очень круто!
Может действительно пулл-реквест сделаете?

**Comment by smalcom** [comment]
Да, конечно. Сделаем-с.

**Comment by smalcom** [comment]
Не пропал, делаю. Работы резко навалило. Плюс там дальше приключения были, потом опишу всё.

**Comment by smalcom** [comment]
https://github.com/abramcumner/xray_re-tools/pull/24
