### ISSUE TITLE
Создать новый релиз

### ISSUE THREAD

**Issue by PavelBlend** [abramcumner/xray_re-tools#5]
Привет, @abramcumner 
Можешь пожалуйста скомпилировать версию конвертера из последнего коммита и зарелизить её? А то пользователям нужно будет самим делать компиляцию (что не каждый умеет). В последних коммитах есть ключ all в режиме skl, который очень нужен.

**Comment by abramcumner** [comment]
Сделано: https://github.com/abramcumner/xray_re-tools/releases/tag/0.1.8
