### ISSUE TITLE
Не работает параметр out при конвертации в skl all

### ISSUE THREAD

**Issue by PavelBlend** [abramcumner/xray_re-tools#6]
В версии 0.1.8 не правильно работает параметр out в режиме skl all. Вот команда:

`converter input_folder\test.omf -skl all -out output_folder\test`

В этом случае конвертер создаст один файл output_folder\test, вместо кучи skl файлов в папке output_folder\test.

Когда KD делал эту функцию, его конвертер работал так:
создаётся папка output_folder, в которой ещё одна папка test и уже в папке test лежат куча skl с оригинальными именами.

Это удобно, когда идёт конвертация целой gamdata папки.

**Comment by abramcumner** [comment]
Надо использовать не ключ -out, а ключ -dir.
Строка запуска при этом будет выглядеть так:
`converter input_folder\test.omf -skl all -dir output_folder\test\`

**Comment by PavelBlend** [comment]
В таком случае пишет:
`output folder does not exist`

Можно ли сделать так, чтобы конвертер сам создавал нужную папку, а не требовал её наличие?

И если всё таки самому создать эту папку, то всё сконвертируется, но имена анимаций будут выглядеть так:
wpn_hand_ak74u_hud_animation_ak74u_draw.skl
wpn_hand_ak74u_hud_animation_ak74u_holster.skl
wpn_hand_ak74u_hud_animation_ak74u_idle.skl

а хотелось бы иметь оригинальные названия, то есть так:
ak74u_draw.skl
ak74u_holster.skl
ak74u_idle.skl

Или сделать эту возможность опционально.

**Comment by PavelBlend** [comment]
Скачал версию 0.1.9 и выдаёт она ошибку:
`output folder does not exist`
Вот команда:
`converter -ogf -skl all wpn_abakan_hud.ogf -dir wpn_abakan_hud`

Папка не создаётся автоматически

**Comment by abramcumner** [comment]
Попробуй версию 0.1.10

**Comment by PavelBlend** [comment]
Спасибо. Теперь работает.
