### ISSUE TITLE
[Вопрос] Как устроен исходный код?

### ISSUE THREAD

**Issue by PavelBlend** [abramcumner/xray_re-tools#8]
Привет, @abramcumner 

Я пишу аддон к блендеру для импорта/экспорта различных форматов 3д моделей и анимаций из сталкера. Но при добавлении новых форматов и возможностей становиться трудно поддерживать проект. Так как структура исходного кода похожа на кашу. Нет чёткого представления картины, как всё сделать правильно. Но посмотрев исходники конвертера от Бардака, я заметил некоторые вещи: код по чтению/записи форматов вынесен в отдельную библиотеку xray_re, а уже утилиты, конвертеры и плагины используют эту библиотеку в своих целях. В общем я хочу сделать так же.

А теперь сами вопросы:

- как расшифровывается название xray_re? Ну про xray это понятно, а вот что означает re?

- как расшифровывается xray_fsl?

- как устроен исходный код xray_re-tools? Как именно код разбит на библиотеки? Я ведь правильно понимаю, что библиотека xray_re описывает форматы, а converter, aiwrapper, xray_fsl, max_object, maya_tools, ms3d_plugin используют классы из xray_re по своим нуждам, и сами хранят только код непосредственно касающийся их предназначения (то есть они не описывают форматы сталкера, а используют описание форматов из xray_re)?

Просто я в Си++ не разбираюсь.

**Comment by abramcumner** [comment]
xray_re: re скорей всего **R**everse **E**ngineering. 
xray_fsl: без понятия что это.

> как устроен исходный код xray_re-tools?

Да, так и есть. Форматы движка и сдк описаны в xray_re и все утилиты ее используют.
