### ISSUE TITLE
При декомпиляции уровня создаются только _part.object и _lod****.object

### ISSUE THREAD

**Issue by Wolf-Heart** [abramcumner/xray_re-tools#9]
При декомпиляции уровня, конвертером xray_re-tools_0.2.0, в папке rawdata\objects\levels\имя_уровня\, создаются только файлы типа _part****.object и _lod****.object и больше ничего.
Нет не _detail****.object, не _fake.object, не _occ.object, не _terrain.object.
Батник стандартный:
converter -level cop:имя_уровня -out имя_уровня -mode le -with_lods -terrain
PAUSE
При декомпиляции конвертером xray_re-tools_0.1.11, все это есть.

**Comment by abramcumner** [comment]
Странно. Вроде ничего не менялось в этом плане. Какая локация декомпилируется?

**Comment by Wolf-Heart** [comment]
Заметил это при декомпиле локации la12_stancia и l11_pripyat вот из этой сборки для СоР:
https://www.playground.ru/files/s_t_a_l_k_e_r_call_of_pripyat_30_lokatsij_dlya_zova_pripyati-194764/
Но потом проверил это на дефолтной Припяти из СоР 1.6.02. Результат был одинаков. Потом проверил эти локи xray_re-tools_0.1.11

**Comment by Wolf-Heart** [comment]
Не декомпелируется локация la01_escape из Lost Alpha. Конвертер выдает ошибку:
```
saving error list
building HOM object
building SOM object
[bug] assertion failed at ..\level_aux_mesh.cxx:94
```
А точнее, не создаются: папка la01_escape и файл la01_escape.level в папке: editors\rawdata\levels
https://i.postimg.cc/j2WLtVVd/1.png
В то время как в папке: editors\rawdata\objects\levels\la01_escape объекты декомпелированы:
https://i.postimg.cc/Cxj17HH5/2.png
Попробовал декомпелировать другой уровень la15_darkscape, декомпил прошел успешно и все необходимые файлы были созданы:
https://i.postimg.cc/sgvxWQwH/3.png
Не знаю, может еще есть такие уровни, которые не декомпилятся, буду тестить, а пока прилагаю полные логи декомпила la01_escape и la15_darkscape: https://yadi.sk/d/jwuzZzU37h3Imw
А так-же на всякий случай уровень la01_escape: https://yadi.sk/d/fhjRrT4RjnewXg
Если еще что необходимо, пиши предоставлю.
